# Generated by Django 5.0.6 on 2024-08-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_completefinalcleaneddata_delete_controlinfos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completefinalcleaneddata',
            old_name='django_id',
            new_name='django_index',
        ),
        migrations.RemoveField(
            model_name='completefinalcleaneddata',
            name='Switch_familyyy',
        ),
        migrations.AddField(
            model_name='completefinalcleaneddata',
            name='Date_validation_SMS',
            field=models.TextField(db_column='Date validation SMS', default=' '),
        ),
        migrations.AlterField(
            model_name='completefinalcleaneddata',
            name='Coeur_fissuré',
            field=models.TextField(db_column='Coeur(s) fissuré(s)'),
        ),
        migrations.AlterField(
            model_name='completefinalcleaneddata',
            name='Date_control',
            field=models.DateTimeField(db_column='Date de contrôle', db_index=True),
        ),
        migrations.AlterField(
            model_name='completefinalcleaneddata',
            name='Date_dernier_renouv',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='completefinalcleaneddata',
            name='Gare_Bifurcation',
            field=models.TextField(db_column='Gare / Bifurcation'),
        ),
        migrations.AlterField(
            model_name='completefinalcleaneddata',
            name='Quote_State',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='completefinalcleaneddata',
            name='Quote_category',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='completefinalcleaneddata',
            name='Quote_measured_value',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='completefinalcleaneddata',
            name='Quote_name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='completefinalcleaneddata',
            name='Ramses_id',
            field=models.TextField(db_column='No. Ident.', db_index=True),
        ),
    ]
