# Generated by Django 5.0.6 on 2024-08-23 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_django_id_completefinalcleaneddata_django_index_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompleteFinalCleanedData',
        ),
    ]
